sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: j
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDjt2bfBt1za8BoyF8J
    access-key-secret: Irozt5ni0GzXqjQ2ITrbmzF7RD4mrN
    bucket-name: yumefusaka
  redis:
    host: localhost
    port: 6379
    password: j
    database: 0
